/**
 * This file is supposedly generated by `${PROJECT_DIR}/build.ts` in the template.
 * But for this exercise, it isn't because `jacob-bot-common` is a private repository that cannot be `npm install` by whose who
 * are not given access to the private repository, hence it is vendored.
 */
import { joinRelativeToPackageJson } from '../../../vendors/jacob-bot-common/dist/src/utils/path';
import { parseKeyValueFileIntoConfiguration } from '../../../vendors/jacob-bot-common/dist/src/configuration';

export type Config = {
  NODE_ENV: string;
  PORT: number;
  NO_COLOR: string;
};

export const appConfigs = parseKeyValueFileIntoConfiguration<Config>(
  joinRelativeToPackageJson(`.env.${process.env.NODE_ENV}`),
);
